### ISSUE TITLE
Missing track in offline mode

### ISSUE THREAD

**Issue by martlin2cz** [martlin2cz/jmop#1]
JMOP crashes when following occurs:
1) Is in offline mode
2) The track file to be played is missing.

Normally, it starts to load it immediatelly, but - since it is offline, it cannot. Hence it crashes in the player. This might be handled somehow, for instance by skipping such track (and displaying the "X" icon in the tracklist).

**Comment by martlin2cz** [comment]
An subtask occured:

````
cz.martlin.jmop.core.misc.ExternalProgramException: Process failed
	at cz.martlin.jmop.core.misc.AbstractProcessEncapusulation.run(AbstractProcessEncapusulation.java:60) 
(...)
Caused by: java.lang.NullPointerException
	at cz.martlin.jmop.core.misc.AbstractProcessEncapusulation.finishProcess(AbstractProcessEncapusulation.java:139) 
````
