### ISSUE TITLE
The progress pane somtimes crashes

### ISSUE THREAD

**Issue by martlin2cz** [martlin2cz/jmop#11]
In some cases, the "progress pane" stops working. It may be solved.

**Comment by martlin2cz** [comment]
It seems it is caused by race condition at hiding showing/hiding the track preparation:

        java.lang.IndexOutOfBoundsException: Index: -1, Size: -1
        at java.util.LinkedList.checkPositionIndex(Unknown Source) ~[?:?]
        at java.util.LinkedList.listIterator(Unknown Source) ~[?:?]
        at com.sun.javafx.collections.ObservableSequentialListWrapper.doAdd(Unknown Source) ~[javafx.base:?]
        at javafx.collections.ModifiableObservableListBase.add(Unknown Source) ~[javafx.base:?]
        at java.util.AbstractList.add(Unknown Source) ~[?:?]
        at cz.martlin.jmop.core.preparer.TrackPreparer.runInForeground(TrackPreparer.java:204) ~[jmop-jwd.jar:?]

This is probably because the "list" (more than just a queue) holding the running operations, is not synchronized, because it is observable.
